[ping]
# How much time to wait before retrying after a failed ping
# Valid time units are "ns", "us" (or "µs"), "ms", "s", "m", "h"
pingRetrySleep = "5s"
# How many times to retry ping before failing and exiting
maxPingRetries = 5
# How much time to wait before retrying after a failed ping
# Valid time units are "ns", "us" (or "µs"), "ms", "s", "m", "h"
timeout = "500ms"

[wallpaper]
# Apply wallpaper after download
ApplyAfterDownload = true
# Delete wallpaper after application
DeleteAfterApply = true
# Don't print anything
QuietMode = false

[chromecast]
# Advanced: You can input google image "deep direct" link parameters here 
# You can find more info here : https://sites.google.com/site/picasaresources/google-photos-1/how-to-get-a-direct-link-to-an-image
# If you don't know what to do, then just leave it as the default (the full image)
parameters = "w0-h0"

[bing]
# Resolution of the base image
# Some valid options are: UHD, 1920x1200, 1920x1080, 1366x768, 1280x768, 1024x768, 800x600, 800x480, 768x1280, 720x1280, 640x480, 480x800, 400x240, 320x240, 240x320
# Every option can be inverted to get a vertical image (eg. 1366x768 => 768x1366) except UHD
URLResolution = "UHD"
# Image quality
quality = 100
# If you have a weird display resolution you can resize the image here by specifying height and width
# Leave both commented if you don't want to resize
# Don't set them to 0, or you won't get an image.  If either = 0, it won't do anything.
# height = 1080
# width = 1920

# List of markets to choose randomly
# These are all the supported markets (i think, there might be more)
# Source: https://learn.microsoft.com/en-us/bing/search-apis/bing-web-search/reference/market-codes
# https://github.com/ORelio/Spotlight-Downloader/blob/master/SpotlightDownloader/Locales.cs has a lot more, not sure if they work for bing tho as they're ment for spotlight
markets = [
    "es-AR",
    "en-AU",
    "de-AT",
    "nl-BE",
    "fr-BE",
    "pt-BR",
    "en-CA",
    "fr-CA",
    "es-CL",
    "da-DK",
    "fi-FI",
    "fr-FR",
    "de-DE",
    "zh-HK",
    "en-IN",
    "en-ID",
    "it-IT",
    "ja-JP",
    "ko-KR",
    "en-MY",
    "es-MX",
    "nl-NL",
    "en-NZ",
    "no-NO",
    "zh-CN",
    "pl-PL",
    "en-PH",
    "ru-RU",
    "en-ZA",
    "es-ES",
    "sv-SE",
    "fr-CH",
    "de-CH",
    "zh-TW",
    "tr-TR",
    "en-GB",
    "en-US",
    "es-US",
]

[spotlight]
# Set true if you want a portrait wallpaper
portrait = false

# This is a list of every (known) supported locale to choose randomly
# Source: https://github.com/ORelio/Spotlight-Downloader/blob/master/SpotlightDownloader/Locales.cs
# Might hardcode in the future
locales = [
    "af-NA",
    "am-ET",
    "ar-AE",
    "ar-BH",
    "ar-DJ",
    "ar-DZ",
    "ar-EG",
    "ar-EH",
    "ar-ER",
    "ar-IL",
    "ar-IQ",
    "ar-JO",
    "ar-KM",
    "ar-KW",
    "ar-LB",
    "ar-LY",
    "ar-MA",
    "ar-MR",
    "ar-OM",
    "ar-PS",
    "ar-QA",
    "ar-SA",
    "ar-SO",
    "ar-SS",
    "ar-TD",
    "ar-TN",
    "ar-YE",
    "as-IN",
    "az-AZ",
    "be-BY",
    "bg-BG",
    "bn-BD",
    "bn-IN",
    "bs-BA",
    "ca-AD",
    "ca-ES",
    "ca-FR",
    "ca-IT",
    "cs-CZ",
    "cy-GB",
    "da-DK",
    "da-GL",
    "de-AT",
    "de-BE",
    "de-CH",
    "de-DE",
    "de-IT",
    "de-LI",
    "de-LU",
    "el-CY",
    "el-GR",
    "en-AG",
    "en-AI",
    "en-AS",
    "en-AT",
    "en-AU",
    "en-BB",
    "en-BE",
    "en-BI",
    "en-BM",
    "en-BS",
    "en-BW",
    "en-BZ",
    "en-CA",
    "en-CC",
    "en-CH",
    "en-CK",
    "en-CM",
    "en-CX",
    "en-CY",
    "en-DE",
    "en-DG",
    "en-DM",
    "en-ER",
    "en-FJ",
    "en-FK",
    "en-FM",
    "en-GB",
    "en-GD",
    "en-GG",
    "en-GH",
    "en-GI",
    "en-GM",
    "en-GU",
    "en-GY",
    "en-HK",
    "en-ID",
    "en-IE",
    "en-IM",
    "en-IN",
    "en-IO",
    "en-JE",
    "en-JM",
    "en-KE",
    "en-KI",
    "en-KN",
    "en-KY",
    "en-LC",
    "en-LR",
    "en-LS",
    "en-MG",
    "en-MH",
    "en-MO",
    "en-MP",
    "en-MS",
    "en-MT",
    "en-MU",
    "en-MW",
    "en-MY",
    "en-NA",
    "en-NF",
    "en-NG",
    "en-NL",
    "en-NR",
    "en-NU",
    "en-NZ",
    "en-PG",
    "en-PH",
    "en-PK",
    "en-PN",
    "en-PR",
    "en-PW",
    "en-RW",
    "en-SB",
    "en-SC",
    "en-SE",
    "en-SG",
    "en-SH",
    "en-SI",
    "en-SL",
    "en-SS",
    "en-SX",
    "en-SZ",
    "en-TC",
    "en-TK",
    "en-TO",
    "en-TT",
    "en-TV",
    "en-TZ",
    "en-UG",
    "en-UM",
    "en-US",
    "en-VC",
    "en-VG",
    "en-VI",
    "en-VU",
    "en-WS",
    "en-ZA",
    "en-ZM",
    "en-ZW",
    "es-AR",
    "es-BO",
    "es-BR",
    "es-BZ",
    "es-CL",
    "es-CO",
    "es-CR",
    "es-DO",
    "es-EA",
    "es-EC",
    "es-ES",
    "es-GQ",
    "es-GT",
    "es-HN",
    "es-IC",
    "es-MX",
    "es-NI",
    "es-PA",
    "es-PE",
    "es-PH",
    "es-PR",
    "es-PY",
    "es-SV",
    "es-US",
    "es-UY",
    "es-VE",
    "et-EE",
    "eu-ES",
    "fa-AF",
    "fi-FI",
    "fo-DR",
    "fo-FO",
    "fr-BE",
    "fr-BF",
    "fr-BI",
    "fr-BJ",
    "fr-BL",
    "fr-CA",
    "fr-CD",
    "fr-CF",
    "fr-CG",
    "fr-CH",
    "fr-CI",
    "fr-CM",
    "fr-DJ",
    "fr-DZ",
    "fr-FR",
    "fr-GA",
    "fr-GF",
    "fr-GN",
    "fr-GP",
    "fr-GQ",
    "fr-HT",
    "fr-KM",
    "fr-LU",
    "fr-MA",
    "fr-MC",
    "fr-MF",
    "fr-MG",
    "fr-ML",
    "fr-MQ",
    "fr-MR",
    "fr-MU",
    "fr-NC",
    "fr-NE",
    "fr-PF",
    "fr-PM",
    "fr-RE",
    "fr-RW",
    "fr-SC",
    "fr-SN",
    "fr-TD",
    "fr-TG",
    "fr-TN",
    "fr-VU",
    "fr-WF",
    "fr-YT",
    "gd-GB",
    "gl-ES",
    "gu-IN",
    "ha-GH",
    "ha-NE",
    "ha-NG",
    "he-IL",
    "hi-IN",
    "hr-BA",
    "hr-HR",
    "hu-HU",
    "hy-AM",
    "id-ID",
    "ig-NG",
    "is-IS",
    "it-CH",
    "it-IT",
    "it-SM",
    "it-VA",
    "ja-JP",
    "ka-GE",
    "kk-KZ",
    "kl-GL",
    "km-KH",
    "kn-IN",
    "ko-KR",
    "ku-IQ",
    "ky-KG",
    "lb-LU",
    "lo-LA",
    "lt-LT",
    "lv-LT",
    "lv-LV",
    "mk-MK",
    "ml-IN",
    "mn-CN",
    "mn-MN",
    "mr-IN",
    "ms-BN",
    "mt-MT",
    "nb-NO",
    "nb-SJ",
    "ne-IN",
    "ne-NP",
    "nl-AW",
    "nl-BE",
    "nl-BQ",
    "nl-CW",
    "nl-NL",
    "nl-SR",
    "nl-SX",
    "or-IN",
    "pa-IN",
    "pa-PK",
    "pl-PL",
    "ps-AF",
    "ps-PK",
    "pt-AO",
    "pt-BR",
    "pt-CH",
    "pt-CV",
    "pt-GQ",
    "pt-GW",
    "pt-LU",
    "pt-MO",
    "pt-MZ",
    "pt-PT",
    "pt-ST",
    "pt-TL",
    "ro-MD",
    "ro-RO",
    "ru-BY",
    "ru-KG",
    "ru-KZ",
    "ru-MD",
    "ru-RU",
    "rw-RW",
    "sd-IN",
    "sd-PK",
    "si-LK",
    "sk-SK",
    "sl-SI",
    "sl-SL",
    "sq-AL",
    "sq-MK",
    "sq-XK",
    "sr-BA",
    "sr-CS",
    "sr-ME",
    "sr-RS",
    "sr-XK",
    "sv-AX",
    "sv-FI",
    "sv-SE",
    "sw-CD",
    "sw-KE",
    "sw-TZ",
    "sw-UG",
    "ta-IN",
    "ta-LK",
    "te-IN",
    "th-TH",
    "ti-ET",
    "tk-TM",
    "tn-BW",
    "tr-CY",
    "tr-TR",
    "ug-CN",
    "ur-IN",
    "ur-PK",
    "uz-AF",
    "uz-UZ",
    "vi-VN",
    "wo-SN",
    "yo-BJ",
    "yo-NG",
    "zh-CN",
    "zh-HK",
    "zh-MO",
    "zh-SG",
    "zh-TW",
]
